### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by R4yGM**

### CODE REVIEW

**Comment by GuillaumeFalourd** [comment]
Hi @R4yGM , how are you doing?

Thank you for opening this PR 👍🏼 

However, I've got some concerns regarding the contribution.

**First**: When adding an action to the repository, the idea is also to add a workflow example using the action, to check it's working as expecting and for people to check the implementation.

**Second**: This action is very specific to Duolingo, and I believe it might be worth creating a new section on the README file that isn't related to generic actions, but specific tools (similar to what I did for security tools).

What do you think?

**Comment by R4yGM** [comment]
Yeah i think that's better, since this is just specifically for duolingo

**Comment by GuillaumeFalourd** [comment]
> I'm good, you? Yeah i think that's better, since this is just specifically for duolingo

Nice! I've updated the repository [CONTRIBUTING](https://github.com/GuillaumeFalourd/useful-actions/blob/main/CONTRIBUTING.md) file if you want to have a look, and I added a **Other Tools Actions** section on the README file 👍🏼

**Comment by R4yGM** [comment]
Alright thanks! now i'm going to update the README

**Pull request closed without merging**
