### PR TITLE
Add action `wretry.action` to section `Useful Actions`

### PR DESCRIPTION
**Pull request by dmvict**

### CODE REVIEW

**Comment by GuillaumeFalourd** [comment]
Hi @dmvict , amd thank you for contributing to this repository 🙂

I observed that you are redirecting to a workflow from your repository on the README file. Would it be possible to add a workflow example on this repository (useful-actions) so that if someone forked the repository they will be able to try it directly on the fork?

I'll update the guidelines to make ot clearer 👍🏼

**Comment by dmvict** [comment]
Please, confirm that all is OK.

**Comment by GuillaumeFalourd** [comment]
Looks good to me 👍🏼 
I'll just add a `workflow_dispatch` event later to execute it once without having to generate a new tag.
Thank you for contributing again 🚀

**Comment by dmvict** [comment]
Thanks!

**Pull request merged**
